# Generated by Django 4.2.1 on 2023-05-11 15:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('methodology', models.CharField(default='', max_length=255)),
                ('inspection_body', models.CharField(max_length=255)),
                ('documentation', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'db_table': 'inspection',
            },
        ),
        migrations.CreateModel(
            name='Level0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iop_code', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=255)),
                ('street', models.CharField(default='', max_length=255)),
                ('initial_km', models.CharField(default='', max_length=50)),
                ('final_km', models.CharField(default='', max_length=50)),
                ('propietary', models.CharField(default='', max_length=255)),
                ('concessionary', models.CharField(default='', max_length=255)),
                ('vigilant_body', models.CharField(default='', max_length=255)),
                ('maintenance_present', models.CharField(choices=[('PR', 'Present'), ('AB', 'Absent'), ('NN', 'Not Noted')], default='NN', max_length=2)),
                ('inspections_present', models.CharField(choices=[('PR', 'Present'), ('AB', 'Absent'), ('NN', 'Not Noted')], default='NN', max_length=2)),
            ],
            options={
                'verbose_name': 'Level 0',
                'verbose_name_plural': 'Level 0 items',
                'db_table': 'level_0',
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('structural_element', models.CharField(default='', max_length=255)),
                ('material', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Piece',
                'verbose_name_plural': 'Pieces',
                'db_table': 'piece',
            },
        ),
        migrations.CreateModel(
            name='ProjectDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('level_0', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='db_demo.level0')),
            ],
            options={
                'verbose_name': 'Project Document',
                'verbose_name_plural': 'Project Documents',
                'db_table': 'project_doc',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('maintenance_type', models.CharField(default='', max_length=255)),
                ('documentation', models.CharField(default='', max_length=255)),
                ('level_0', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='db_demo.level0')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenance entries',
                'db_table': 'maintenance',
            },
        ),
        migrations.CreateModel(
            name='Level1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default='', max_length=255)),
                ('km', models.CharField(default='', max_length=255)),
                ('tecnico', models.CharField(default='', max_length=255)),
                ('inspection_date', models.DateField(default='')),
                ('structure_type', models.CharField(choices=[('AM', 'Arco in Muratura'), ('OT', 'Other')], default='OT', max_length=2)),
                ('structure_type_other', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('inspection', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='db_demo.inspection')),
            ],
            options={
                'verbose_name': 'Level 1',
                'verbose_name_plural': 'Level 1 items',
                'db_table': 'level_1',
            },
        ),
        migrations.AddField(
            model_name='inspection',
            name='level_0',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='db_demo.level0'),
        ),
        migrations.CreateModel(
            name='FormDefects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_number', models.IntegerField(default=1)),
                ('level_1', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='db_demo.level1')),
                ('piece', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='db_demo.piece')),
            ],
            options={
                'verbose_name': 'Form of Defects',
                'verbose_name_plural': 'Forms of Defects',
                'db_table': 'form_defects',
                'unique_together': {('piece', 'piece_number', 'level_1')},
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=255)),
                ('g', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('piece', models.ManyToManyField(to='db_demo.piece')),
            ],
            options={
                'verbose_name': 'Defect',
                'verbose_name_plural': 'Defects',
                'db_table': 'defect',
            },
        ),
        migrations.CreateModel(
            name='BridgeGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('level_0', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='db_demo.level0')),
            ],
            options={
                'verbose_name': 'Bridge Geometry',
                'verbose_name_plural': 'Bridges geometries',
                'db_table': 'bridge_geometry',
            },
        ),
        migrations.CreateModel(
            name='FormDefectsAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('k1', models.CharField(choices=[('0,2', '0,2'), ('0,5', '0,5'), ('1', '1'), ('None', 'Empty')], default=None, max_length=10, null=True)),
                ('k2', models.CharField(choices=[('0,2', '0,2'), ('0,5', '0,5'), ('1', '1'), ('None', 'Empty')], default=None, max_length=10, null=True)),
                ('n_photo', models.CharField(default='', max_length=255)),
                ('ps', models.BooleanField(default=None, null=True)),
                ('incomplete_reason', models.CharField(choices=[('NA', 'Non Applicabile'), ('NR', 'Non Rilevabile'), ('NP', 'Non Present'), ('None', 'Empty')], default=None, max_length=10, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('defect', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='db_demo.defect')),
                ('form_defects', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='db_demo.formdefects')),
            ],
            options={
                'verbose_name': 'Answers of Form of Defects',
                'verbose_name_plural': 'Answers of Form of Defects',
                'db_table': 'form_defects_answer',
                'unique_together': {('defect', 'form_defects')},
            },
        ),
    ]
